# Generated by Django 2.1 on 2018-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_edit', models.DateTimeField(auto_created=True)),
                ('user_create', models.DateTimeField(auto_created=True)),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=20)),
                ('cv_file', models.FileField(upload_to='')),
                ('ava', models.ImageField(upload_to='')),
            ],
        ),
    ]
